trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:

- stage: deployToDev
  displayName: Deploy to DEV  
  jobs:
    - deployment: dev
      displayName: Deploy to aws-postgresql

      environment: aws-dev

      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self

            - task: CmdLine@2
              displayName: clone postgresql samples repo
              inputs:
                script: |
                  git clone https://github.com/srinivas-byte/yuniql_build $(Build.SourcesDirectory)\yuniql
            - task: UseYUNIQLCLI@1
              displayName: yuniql install
              inputs:
                version: 'latest'


            - task: RunYUNIQLCLI@1
              displayName: yuniql run
              inputs:
                version: 'latest'
                connectionString: 'Server=tcp:alpha1011.database.windows.net,1433;Persist Security Info=False;User ID=srini;Password=@Alpha1kills@beta2wins;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
                workspacePath: '$(Build.SourcesDirectory)\yuniql_test'
                targetPlatform: 'sqlserver'
                additionalArguments: '--debug'
                autoCreateDatabase: 'true'
                
    