trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:

- stage: deployToDev
  displayName: Deploy to DEV  
  jobs:
    - deployment: dev
      displayName: Deploy to aws-postgresql

      environment: aws-dev

      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self

            - task: CmdLine@2
              displayName: clone postgresql samples repo
              inputs:
                script: |
                  git clone https://github.com/srinivas-byte/yuniql_build $(Build.SourcesDirectory)\yuniql
            - task: UseYUNIQLCLI@1
              displayName: yuniql install
              inputs:
                version: 'latest'


            - task: RunYUNIQLCLI@1
              displayName: yuniql run
              inputs:
                version: 'latest'
                connectionString: 'Server=alpha101.postgres.database.azure.com;Database=test;Port=5432;User Id=srini@alpha101;Password=@Alpha1kills@beta2;'
                workspacePath: '$(Build.SourcesDirectory)\yuniql_test'
                targetPlatform: 'PostgreSql'
                additionalArguments: '--debug'